### ISSUE TITLE
Review 'wrap_to_coroutine'.

### ISSUE THREAD

**Issue by greschd** [FrescolinoGroup/pyasynctools#1]

**Comment by mskoenz** [comment]
please link to relevant file/commit

**Comment by greschd** [comment]
Made it into a PR: #2.

**Comment by mskoenz** [comment]
Isn't it possible to do a review without a pull request? I'm fine with it being in the Issue category...

**Comment by mskoenz** [comment]
solved by #2

**Comment by greschd** [comment]
One could, but PR has certain nice features (comment on code, view diff).
